# Generated by Django 5.2.4 on 2025-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='total_slots',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='reserved_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
